# Generated by Django 3.2.7 on 2021-09-15 16:05

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_type', models.CharField(choices=[('cours', 'cours'), ('Traveaux derigie', 'Traveaux derigie'), ('Traveaux pratique', 'Traveaux pratique'), ('exam', 'exam')], default='choices ...', max_length=200)),
                ('name', models.CharField(max_length=150)),
                ('moduleid', models.IntegerField(default=0)),
                ('semesterid', models.IntegerField(default=0)),
                ('filierid', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('pdf', models.FileField(upload_to=courses.models.user_directory_path)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Filier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('title', models.CharField(max_length=40)),
                ('count', models.IntegerField(default=0)),
                ('show', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('semmesterid', models.IntegerField(blank=True, default=0, null=True)),
                ('filierid', models.IntegerField(blank=True, default=0, null=True)),
                ('ccount', models.IntegerField(default=0)),
                ('Tdcount', models.IntegerField(default=0)),
                ('tpcount', models.IntegerField(default=0)),
                ('ecount', models.IntegerField(default=0)),
                ('show', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('count', models.IntegerField(default=0)),
                ('filierId', models.IntegerField(default=0)),
                ('show', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
