# Generated by Django 3.2.7 on 2021-09-14 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='filierid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.filier'),
        ),
        migrations.AlterField(
            model_name='module',
            name='semmesterid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.semester'),
        ),
    ]
