# Generated by Django 3.2.7 on 2021-09-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210914_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='filierid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='semmesterid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
