# Generated by Django 3.2.7 on 2021-09-14 15:00

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210914_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='filier',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='courses',
            name='C_type',
            field=models.CharField(choices=[('cours', 'cours'), ('Traveaux derigie', 'Traveaux derigie'), ('Traveaux pratique', 'Traveaux pratique'), ('exam', 'exam')], default='choices ...', max_length=200),
        ),
        migrations.AlterField(
            model_name='courses',
            name='pdf',
            field=models.FileField(blank=None, null=True, upload_to=courses.models.user_directory_path),
        ),
    ]
