# Generated by Django 3.2.7 on 2021-09-14 20:52

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210914_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='pdf',
            field=models.FileField(upload_to=courses.models.user_directory_path),
        ),
    ]
