# Generated by Django 3.2.5 on 2021-08-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('pdf', models.FileField(upload_to='filier/Coure')),
                ('moduleid', models.IntegerField(default=0)),
                ('semesterid', models.IntegerField(default=0)),
                ('filierid', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=30)),
                ('title', models.CharField(max_length=40)),
                ('count', models.IntegerField(default=0)),
                ('show', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('semmesterid', models.IntegerField(blank=True, default=0, null=True)),
                ('filierid', models.IntegerField(blank=True, default=0, null=True)),
                ('ccount', models.IntegerField(default=0)),
                ('Tdcount', models.IntegerField(default=0)),
                ('tpcount', models.IntegerField(default=0)),
                ('ecount', models.IntegerField(default=0)),
                ('show', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('count', models.IntegerField(default=0)),
                ('filierId', models.IntegerField(default=0)),
                ('show', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
