# Generated by Django 3.2.5 on 2021-08-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='C_type',
            field=models.CharField(choices=[('cours', 'cours'), ('Td', 'Traveaux derigie'), ('Tp', 'Traveaux pratique'), ('exam', 'Exam')], default='choices ...', max_length=200),
        ),
    ]
