# Generated by Django 3.2.5 on 2021-08-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduction', '0002_courses_c_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='filier',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
