# Generated by Django 3.2.5 on 2021-08-15 09:16

from django.db import migrations, models
import eduction.models


class Migration(migrations.Migration):

    dependencies = [
        ('eduction', '0003_auto_20210810_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='create_date',
            field=models.DateTimeField(auto_created=True, default='00:00'),
        ),
        migrations.AddField(
            model_name='module',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='C_type',
            field=models.CharField(choices=[('cours', 'cours'), ('Traveaux derigie', 'Traveaux derigie'), ('Traveaux pratique', 'Traveaux pratique'), ('exam', 'Exam')], default='choices ...', max_length=200),
        ),
        migrations.AlterField(
            model_name='courses',
            name='pdf',
            field=models.FileField(upload_to=eduction.models.user_directory_path),
        ),
    ]
