# Generated by Django 3.2.5 on 2021-08-15 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduction', '0004_auto_20210815_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='create_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime.now),
        ),
    ]
