# Generated by Django 3.2.5 on 2021-08-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduction', '0006_alter_module_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='create_date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
