# Generated by Django 3.2.5 on 2021-08-15 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduction', '0008_alter_module_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='create_date',
            new_name='created_datetime',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='update_date',
            new_name='update_datetime',
        ),
    ]
