# Generated by Django 3.2.5 on 2021-08-15 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduction', '0009_auto_20210815_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='created_datetime',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='update_datetime',
            new_name='update_date',
        ),
    ]
