# Generated by Django 3.2.5 on 2021-08-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduction', '0010_auto_20210815_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='create_date',
        ),
    ]
