# Generated by Django 3.2.5 on 2021-08-15 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduction', '0011_remove_module_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='update_date',
        ),
    ]
